import './globals.css'
import NavBar from './components/navBar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <NavBar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
